### PR TITLE
Update Beacon create modal and instance fetching semantics

### PR DESCRIPTION
**Pull request by ngmiller**
### What

These changes fix instance fetching under a beacon. Previously, we were sending the `Name` field of the beacon docker instance instead of the `Alias`. The alias field is now required for beacon creation. See the `Add Beacon` modal under `/beacons`. Since all fields are required for a beacon create, we now provide validation errors before sending the request over. These only check for the existence of the fields, not their format (i.e. no regex to check for a valid IP format)

### How

* Modified all links from `{{ instance.Name }}` to `{{ instance.Alias }}` coming back from the lighthouse response.
* Validation errors are handled partially by angular - the form itself is assigned a `$scope` attribute used to store validation state. These values are checked and used determine if an error style needs to be applied to a form group.
* As a bonus, removed the now unused `instances.html` template, since this functionality is now under control of the beacons page.

### Dependency

Must be merged after https://github.com/lighthouse/lighthouse/pull/45 is merged into lighthouse/master.

### Example validation error

screen shot 2015-03-03 at 2 59 43 pm

### CODE REVIEW

**Comment by ngmiller** [comment]
@lighthouse/owners I'd like to look into handling form validation in the "angular way" tomorrow to catch an empty alias and the like, but this is ready for a first glance.

**Comment by ngmiller** [comment]
@theMagicalKarp @zach-taylor This is ready for a full review and test. Note the beacon create modal no longer fades in or out and does not change the background color when shown. I had trouble finding a way to reconcile the angular validation states with the auto-dismiss feature of the modal. The "right" way would be to create a directive that can monitor scope attributes and modify the DOM accordingly, but I figured a simple scope boolean (`$scope.submitting`) would suffice for now.

**Comment by robertsheehy-wf** [comment]
+1

**Comment by zach-taylor** [comment]
+1

**Pull request merged**
