### PR TITLE
Provider / Beacon refactor

### PR DESCRIPTION
**Pull request by ngmiller**
### What

Adds support for viewing beacons and the instances contained within them. Users may now also add a new beacon by providing the IP address/port along with the generated auth token.

### How

* created a new beaconController/Service/Model trio to support the new beacons page
* pulled instance listing out of the instanceModel - now the responsibility of beaconModel. Essentially, all incoming beacons are assigned a unique, sequential ID and the incoming instances are stored according to that ID
* instanceServices dispatches instance lists based on a given beacon

A successful login now routes users to `/beacons` by default.

Depends on https://github.com/lighthouse/lighthouse/pull/40 and will allow https://github.com/lighthouse/lighthouse/pull/34 to go through.

Credit to @zach-taylor for the initial framework

### CODE REVIEW

**Comment by ngmiller** [comment]
@lighthouse/owners

**Comment by cmbrose** [comment]
@ngmiller is it possible to fix that VM name vs alias issue in this PR?  I can update https://github.com/lighthouse/lighthouse/pull/40 to send aliases as well if you need.

**Comment by cmbrose** [comment]
Other than that, +1.  We'll want to merge in https://github.com/lighthouse/lighthouse/pull/40 and https://github.com/lighthouse/lighthouse/pull/34 at the same time as this one.

**Comment by zach-taylor** [comment]
+1

**Pull request merged**
