### PR TITLE
Display containers and images for a specific Docker host

### PR DESCRIPTION
**Pull request by ngmiller**
## What

* Can view images and containers for a specific Docker host
* Set up some initial filters for user viewing pleasure (i.e. unix epoch dates to relative dates)
* Refactored Docker API service. All functionality is hosted out of `dockerService`

## Why

* Core functionality

## How

* Updated instance templates
* Added `transform` module for data filtering
* Consolidated Docker API calls into a nested object returned by `dockerService`

## Todo

These UI updates are certainly not final. I'd love to hear any suggestions for later work. Just wanted to get the concept up and running.

screen shot 2015-01-27 at 10 50 59 pm

Note the green checkmark implies the `instance.canAccessDocker` field is true. A red "X" is displayed when that field is false.

### CODE REVIEW

**Comment by ngmiller** [comment]
@lighthouse/owners Ready for review. If you have time, pulling down and testing manually would be greatly appreciated!

**Comment by ngmiller** [comment]
@theMagicalKarp @zach-taylor Any objections here?

**Comment by robertsheehy-wf** [comment]
I'm happy +1

**Comment by zach-taylor** [comment]
+1

**Pull request merged**
