### PR TITLE
Support for full page refresh

### PR DESCRIPTION
**Pull request by ngmiller**
These changes make it possible for a user to do a full page refresh without losing their authorization state. Utilizing `$window.sessionStorage`, we are able to keep a users auth state around and check those values on app startup (see the appInit() function in `app.js`). Upon logout and window/browser close, those values are removed from the session storage.

This also lays the groundwork for properly handling un-authed requests.

### Coding conventions

In order to support page reloads, controllers associated with a view are now responsible for calling the services needed to dispatch and populate the store(s) associated with the controller. See `app/js/instances/containerController.js` for an example of this. Note that the call to `dockerService.containers.inspect(...)` was previously called in `instanceController` but is now tied to the controller where the data is actually needed.

### Notes

* updated the storage semantics for the `instanceModel`

### Testing

Once logging in, one should be able to do a full browser refresh (ctrl-R and the like) without losing their auth state.

### CODE REVIEW

**Comment by ngmiller** [comment]
@lighthouse/owners

**Comment by zach-taylor** [comment]
Nice! Works for me. +1

**Comment by robertsheehy-wf** [comment]
+1

**Comment by ngmiller** [comment]
FYI, I need to refactor this a bit - more changes coming

**Comment by ngmiller** [comment]
@zach-taylor @theMagicalKarp This should be good to go now. Would you be so kind to give one more glance? Thanks!

**Comment by robertsheehy-wf** [comment]
cool sessionStorage +1

**Comment by zach-taylor** [comment]
Looks good. +1

**Pull request merged**
